name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: mikeysan/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Well, this is new. I am not used to anyone contributing to my projects. Thank you.'' first issue'
        pr-message: 'Your contribution is greatly appreciated'' first pr'
